name: cramp4
description: "A video compression and encoding tool."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  file_picker: ^11.0.2
  shared_preferences: ^2.3.2
  google_fonts: ^8.0.2
  desktop_drop: ^0.7.1
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_windows_video: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
